# Base URL
baseurl = "https://system32.blog/"

# Pagination
paginate = 10

# Theme
theme = "hugo-clarity"

# Disqus Comments
disqusShortname = "system32-blog"

# Default Language
DefaultContentLanguage = "en"

# Settings
[taxonomies]
categories = "categories"
tag = "tags"
series = "series"