matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:  
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  - pyspelling.filters.context:
      context_visible_first: true
      #escapes: '\\[\\`~]'
      delimiters:
      - open: '^\+{3}$'
        close: '^\+{3}$'
  sources:
  - '**/*.md'
  default_encoding: utf-8